version: "3.7"

# This compose file is meant to be used with VS Code Dev Containers

services:
  api:
    container_name: minipedia-api
    build: ./node
    environment:
      - PORT=3001
      - DB_CONN_STR=mongodb://root:example@minipedia-library:27017/
    ports:
      - 3001:3001
    networks:
      - api-db
    expose:
      - 3001
    volumes:
      - ./node:/code
    tty: true # Keep the container running for development.
    depends_on:
      - mongodb

  mongodb:
    container_name: minipedia-library
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - 27017:27017
    networks:
      - api-db
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:


networks:
  api-db:
